export const FETCH_SERVICE = 'FETCH_SERVICE';
export const ADD_SELECTED = 'ADD_SELECTED';
export const FILTER_TYPES = 'FILTER_TYPES';
export const FILTER_BRANDS = 'FILTER_BRANDS';
export const FILTER_BRAND_COLORS = 'FILTER_BRAND_COLORS';

